### ISSUE TITLE
Optimize arena images

### ISSUE THREAD

**Issue by AmirSavand** [martincarrera/clash-royale-api#60]
Some images have a lot of **space around them**, which is bad and makes images size a bit larger.
In other words, having spaces around images is **bad practice**.

I will make a **pull request** for this one **myself**! (if that's ok)

**Comment by MaherFa** [comment]
for arenas that was intentional, they share the size of the largest one and are all aligned by Base,  i was thunking itll be cool like that, looking back I regret that.

So yeah I agree.
Chests are affected by semi transparent pixels from the original texture files, you can crop them if you have the time. But I'm planning on responding them later

**Comment by AmirSavand** [comment]
Alright, I'll crop em all, I use a tool that auto-crops images, so it'll be super quick.
I'll make a pull after my work.

**Comment by AmirSavand** [comment]
Pull is on the way
