### ISSUE TITLE
Consume API via HTTPS

### ISSUE THREAD

**Issue by ikenami** [martincarrera/clash-royale-api#98]
It would be nice if we could consume the API using HTTPS instead of HTTP without the "insecure" warning popping up. Any plans to do so?

**Comment by martincarrera** [comment]
Hi @ikenami! I have the HTTPS version [here](https://clashapi.now.sh/).

The problem is that Heroku does not provide HTTPS by default, and the hosting I'm using to get HTTPS (now.sh) is not 100% stable, so I am not quite comfortable with migrating the app yet.

You can still use https://clashapi.now.sh/ to consume the API using HTTPS, as it's a exact replica of the API in clashapi.xyz

Also, check this issue: #83
